### ISSUE TITLE
GitHub Actions & npm publish

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/app-node-env#8]
# GitHub Actions & npm publish

> auto publish

https://github.com/xgqfrms/app-node-env/actions/new

```yml

- name: NPM Publish
  # You may pin to the exact commit or the version.
  # uses: JS-DevTools/npm-publish@18351461ae08dde235c0ccee0633ec905f0b9a52
  uses: JS-DevTools/npm-publish@v1

```

https://github.com/xgqfrms/app-node-env/blob/master/.github/workflows/auto-publish.yml
